steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/boligportal-scraper:latest', '-f', 'Dockerfile.gcloud.job', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/boligportal-scraper:latest']

images:
  - 'gcr.io/$PROJECT_ID/boligportal-scraper:latest'